DiveintoCode-corp/DIC_thema_lesson

app/assets/javascripts/blogs.coffee, app/assets/stylesheets/blogs.scss, app/controllers/blogs_controller.rb, app/helpers/blogs_helper.rb, app/views/blogs/index.html.erb, test/controllers/blogs_controller_test.rb
=> blogs contlloler を作成しました

app/models/blog.rb, db/migrate/20160918111504_create_blogs.rb, db/schema.rb, test/factories/blogs.rb, test/models/blog_test.rb
・ブログモデル作成
・テーブルのカラムは以下の通りです。
①title string型
②content text型
③user_id references型
=> ブログモデル・テーブル作成

config/routes.rb
=> blogのrouting機能を設定しました

app/models/blog.rb
=> blogバリデーション

app/views/layouts/_footer.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb
#3 
・ヘッダーパーシャルの作成 _header.html
・フッダーパーシャルの作成_footer.html
・フッターにコピーライトを追記
=> ヘッダーとフッターを作成する #3

app/models/blog.rb, db/migrate/20161002043921_create_blogs.rb, test/factories/blogs.rb, test/models/blog_test.rb
#4 
・blogモデルを作成
・作成したblogモデルに"before_action :authenticate_user!"を追加
・マイグレーションファイルに以下を追加
　t.string :title
　t.text :content
　t.references :user
=> [fixed] blogモデルを追加

app/assets/javascripts/blogs.coffee, app/assets/stylesheets/blogs.scss, app/helpers/blogs_helper.rb, app/views/blogs/_form.html.erb, app/views/blogs/edit.html.erb, app/views/blogs/index.html.erb, app/views/blogs/new.html.erb, app/views/blogs/show.html.erb, config/routes.rb, test/controllers/blogs_controller_test.rb
#65 
app/views/blogs内に以下のビューファイルを作成する
index.html.erb
show.html.erb
new.html.erb
edit.html.erb
_form.html.erb
=> [fixed] ブログのビューファイルを作成する

Gemfile.lock, app/models/user.rb, db/schema.rb
#20 
userモデルに以下の通り追記しました。
has_many :blogs, :dependent => destroy
これで合ってますでしょうか・・・？
=> [fixed] ユーザーが削除されるとそれに紐づくブログも削除される

app/controllers/blogs_controller.rb, test/controllers/blogs_controller_test.rb
=> [Fixed]ブログコントローラーの作成

app/views/layouts/_footer.html.erb, app/views/layouts/application.html.erb
issue#3
やった事
・_header.html.erb作成　⇒　空ファイル
・_footer.html.erb作成　⇒　指定された一文を挿入
・application.html.erb　⇒　bodyの中に、<%= render 'header' %>、<%= render 'footer' %>を追記
=> 【Fixed】ヘッダーとフッターを作成する

app/models/blog.rb, db/schema.rb
#21 
app/models/blog.rbに記載しました。
タイトル：必須
内容：必須・文字数140字以内
=> [Fixed]ブログのバリデーションを設定する

app/controllers/blogs_controller.rb
#8 
・ブログのストロングパラメータをprivate内で定義
=> [Fixed]ブログのストロングパラメータを定義

app/controllers/blogs_controller.rb, app/models/blog.rb
#19 
blogモデルに以下の通り追記しました
before_action :authenticate_user!
=> [fixed] ログインしてないとブログを見られないようにする

app/assets/javascripts/top.coffee, app/assets/stylesheets/top.scss, app/controllers/top_controller.rb, app/helpers/top_helper.rb, app/views/top/index.html.erb, config/routes.rb, test/controllers/top_controller_test.rb
=> [fixed] トップ画面作成

app/assets/javascripts/blogs.coffee, app/assets/stylesheets/blogs.scss, app/assets/stylesheets/scaffolds.scss, app/controllers/blogs_controller.rb, app/helpers/blogs_helper.rb, app/models/blog.rb, app/views/blogs/_blog.json.jbuilder, app/views/blogs/_form.html.erb, app/views/blogs/edit.html.erb, app/views/blogs/index.html.erb, app/views/blogs/index.json.jbuilder, app/views/blogs/new.html.erb, app/views/blogs/show.html.erb, app/views/blogs/show.json.jbuilder, config/routes.rb, db/migrate/20161029073819_create_blogs.rb, db/schema.rb, test/controllers/blogs_controller_test.rb, test/factories/blogs.rb, test/models/blog_test.rb
#5
・title string型
・content text型
=> [fixed]ブログ機能を作成する

app/controllers/blogs_controller.rb
#19
before_action :authenticate_user!
=> [fixed] ログインしていないとブログが見られない

app/models/blog.rb, app/models/user.rb, db/schema.rb
=> [fiexed]アソシエーション定義

app/models/blog.rb
#21 
-[] blog.rbに下記追加
　　
validates :title, precense: true
validates :content, length: { maximum: 140 }
=> [fixed] ブログのバリデーションを設定する

app/views/layouts/_header.html.erb
#1 
-[] _header.html.erbに下記追加
<% if user_signed_in? %>
<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "ログイン", new_user_session_path %>
<% end %>
=> [fixed]ヘッダーにログインとログアウトのリンクを作る

app/controllers/blogs_controller.rb, app/views/blogs/index.html.erb
=> [fixed]ブログに投稿者追記
